name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - images/gglogo.png

  fonts: 
      - family: Space Mission
        fonts:
          - asset: fonts/space-mission.regular.ttf
            weight: 400
      - family: Roboto
        fonts:
          - asset: fonts/roboto-slab.regular.ttf
            weight: 200